name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      UID_FILENAME: faf-uid.exe
      UID_PLATFORM: "win32"
      MXE_DIR: /usr/lib/mxe
      MXE_TARGET: x86_64-w64-mingw32.static

    steps:
      - uses: actions/checkout@v4
      - name: Configure MXE
        run: |
          apt-get update
          # from https://mxe.cc/#requirements
          apt-get install \
              autoconf \
              automake \
              autopoint \
              bash \
              bison \
              bzip2 \
              flex \
              g++ \
              g++-multilib \
              gettext \
              git \
              gperf \
              intltool \
              libc6-dev-i386 \
              libgdk-pixbuf2.0-dev \
              libltdl-dev \
              libgl-dev \
              libpcre3-dev \
              libssl-dev \
              libtool-bin \
              libxml-parser-perl \
              lzip \
              make \
              openssl \
              p7zip-full \
              patch \
              perl \
              python3 \
              python3-distutils \
              python3-mako \
              python3-packaging \
              python3-pkg-resources \
              python-is-python3 \
              ruby \
              sed \
              sqlite3 \
              unzip \
              wget \
              xz-utils \
          # faf-uid dependencies
              mxe-$MXE_TARGET-jsoncpp \
              mxe-$MXE_TARGET-cryptopp \
              mxe-$MXE_TARGET-icu4c

      - name: Build
        run: |
          $MXE_DIR/usr/bin/$MXE_TARGET-cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCRYPTOPP_LIBRARIES=/usr/lib/mxe/usr/$MXE_TARGET/lib/libcryptopp.a \
            -DCRYPTOPP_INCLUDE_DIRS=/usr/lib/mxe/usr/$MXE_TARGET/include \
            -DUID_SKIP_LEGACY=On \
            # -DUID_PUBKEY_BYTES=$(../encode_openssl_modulus.py $(openssl rsa -noout -inform PEM -in ../faf_pub.pem -pubin -modulus))
            -B build
          make -C build

      - name: Create draft release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ github.event.inputs.version }}
          draft: true
          prerelease: true
          artifacts: "*.exe"
